# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All SLE boxes are managed locally.
  config.vm.box = "oS-nox-Leap-42.2-20161230"
  config.vm.box_check_update = false

  # If not for other "serious" purpose, keep it simple
  config.ssh.insert_key = false

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # TODO we need better way to keep track of all those VMs.
  config.vm.network "private_network", ip: "192.168.56.30"
  config.vm.hostname = "oS-nox-Leap-42.2-20161230"

  # config.vm.network "public_network"

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
  end

  # config.vm.provision "shell", inline: <<-SHELL
  # SHELL
end
