# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All SLE boxes are managed locally.
  config.vm.box = "sles-12-sp2-20161217"
  config.vm.box_check_update = false

  config.ssh.insert_key = false

  config.vm.network "private_network", type: "dhcp"
  config.vm.hostname = "sles12sp2"

  config.vm.provider "virtualbox" do |vb|
    # NOTE this is a box with GUI
    vb.gui = true

    vb.memory = "2048"
  end

  # config.vm.provision "shell", inline: <<-SHELL
  # SHELL
end
