# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All SLE boxes are managed locally.
  config.vm.box = "sles-12-sp2-20161217"
  config.vm.box_check_update = false

  # If not for other "serious" purpose, keep it simple
  config.ssh.insert_key = false

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # TODO we need better way to keep track of all those VMs.
  config.vm.network "private_network", ip: "192.168.56.10"

  # config.vm.network "public_network"

  # config.vm.synced_folder "../data", "/vagrant_data"

  #
  config.vm.provider "virtualbox" do |vb|
    # NOTE sometimes, we need to debug graphical issues.
    # vb.gui = true

     vb.memory = "2048"
  end

  # config.vm.provision "shell", inline: <<-SHELL
  # SHELL
end
