# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # For making box purpose, do not insert new key
  config.ssh.insert_key = false

  config.vm.box = "ogarcia/archlinux-x64"

  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    # Enough RAM to avoid installation errors
    vb.memory = "1024"
  end

  # NOTE shell script should be in unix line ending style
  config.vm.provision "shell", path: 'crystal-provision.sh'
end
