# -*- mode: ruby -*-
# vi: set ft=ruby :

# NOTE vanila use the base box beno/ubuntu-16.04

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.box_check_update = false
  # NOTE No new keys s.t. easy access for non-host machines (only need vagrant key)
  config.ssh.insert_key = false

  ## NOTE Vagrant's dhcp is default to "172.28.128.X".
  # The DHCP server is crystal.cw (172.28.128.77), ranging from 172.28.128.100-254.
  # Forced domain '.cv.' with crystal.cw as Authority
  config.vm.network "private_network", type: "dhcp"
  config.vm.hostname = "bento-ubuntu-xenial"

  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    vb.memory = "1024"
    # TODO if not good enough, we need to set up a local ntp server
    vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
  end
end
