# -*- mode: ruby -*-
# vi: set ft=ruby :

# NOTE vanila use the base box beno/ubuntu-16.04

load File.expand_path("../../tools/Vagrantfile.tpl/common.inc", __FILE__)

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config_common(config)
  config_vm_network_private_network_dhcp(config)

  config.vm.hostname = "bento-ubuntu-xenial"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    # TODO if not good enough, we need to set up a local ntp server
    vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
  end
end

