# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All SLE boxes are managed locally.
  config.vm.box = "ses4-ceph-deploy-20161223"
  config.vm.box_check_update = false

  # If not for other "serious" purpose, keep it simple
  config.ssh.insert_key = false

  # Network convention: keep them within 50-59.
  config.vm.define :admin, primary: true do |admin|
    admin.vm.network "private_network", ip: "192.168.56.50"
    admin.vm.hostname = "admin"
  end
  # NOTE: let's say admin is node0
  config.vm.define :node1 do |node1|
    node1.vm.network "private_network", ip: "192.168.56.51"
    node1.vm.hostname = "node1"
  end
  config.vm.define :node2 do |node2|
    node2.vm.network "private_network", ip: "192.168.56.52"
    node2.vm.hostname = "node2"
  end
  config.vm.define :node3 do |node3|
    node3.vm.network "private_network", ip: "192.168.56.53"
    node3.vm.hostname = "node3"
  end
  config.vm.define :node4 do |node4|
    node4.vm.network "private_network", ip: "192.168.56.54"
    node4.vm.hostname = "node4"
  end

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
  end

  # config.vm.provision "shell", inline: <<-SHELL
  # SHELL
end
