# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All SLE boxes are managed locally.
  config.vm.box = "ses4-ceph-deploy-20161223"
  config.vm.box_check_update = false

  # If not for other "serious" purpose, keep it simple
  config.ssh.insert_key = false

  # Network convention: keep them within 50-59.
  config.vm.define :admin, primary: true do |admin|
    admin.vm.network "private_network", ip: "192.168.56.50"
    admin.vm.hostname = "admin"
    config.vm.network "forwarded_port", guest: 22, host: 7000, id: 'ssh'
  end
  # NOTE: let's say admin is node0
  # TODO: ip should be dhcp now
  config.vm.define :node1 do |node1|
    node1.vm.network "private_network", ip: "192.168.56.51"
    node1.vm.hostname = "node1"
    config.vm.network "forwarded_port", guest: 22, host: 7001, id: 'ssh'
  end
  config.vm.define :node2 do |node2|
    node2.vm.network "private_network", ip: "192.168.56.52"
    node2.vm.hostname = "node2"
    config.vm.network "forwarded_port", guest: 22, host: 7002, id: 'ssh'
  end
  config.vm.define :node3 do |node3|
    node3.vm.network "private_network", ip: "192.168.56.53"
    node3.vm.hostname = "node3"
    config.vm.network "forwarded_port", guest: 22, host: 7003, id: 'ssh'
  end
  config.vm.define :node4 do |node4|
    node4.vm.network "private_network", ip: "192.168.56.54"
    node4.vm.hostname = "node4"
    config.vm.network "forwarded_port", guest: 22, host: 7004, id: 'ssh'
  end

  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    vb.memory = "2048"

    # NOTE make time syncing more strict, if not working, we need ntp
    vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
  end

  # config.vm.provision "shell", inline: <<-SHELL
  # SHELL
end
