# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # NOTE still use ses3 builder it applies to master ceph as well for now  at least
  config.vm.box = "ses3-builder-20170109"
  config.vm.box_check_update = false

  # If not for other "serious" purpose, keep it simple
  config.ssh.insert_key = false

  # TODO we need better way to keep track of all those VMs.
  config.vm.network "private_network", ip: "192.168.56.66"
  config.vm.hostname = "ses4-builder"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "8192"
  end

  # config.vm.provision "shell", inline: <<-SHELL
  # SHELL
end
