#!/bin/sh

# A script to sync generated Ansible files (inventory, variables) with Ansible
# control machines
# Currently:
# 1. Sync inventory file

ANSIBLE_FILES=./ansible_files
INVENTORY=$ANSIBLE_FILES/hosts

rm $INVENTORY
vagrant validate

scp $ANSIBLE_FILES/* vagrant@crystal.cw:/opt/ssd/sources/ceph-ansible/
