# -*- mode: ruby -*-
# vi: set ft=ruby :

# NOTE: main box for daily use, containing comments for refs.
Vagrant.configure(2) do |config|
  config.vm.box = "crystal-maker"

  config.vm.box_check_update = false
  config.ssh.insert_key = false

  config.vm.hostname = "crystal"
  # NOTE now this box is also the dhcp and dns server for the internal network
  config.vm.network "private_network", ip: "172.28.128.77"

  # NOTE Same as default, but mark host_ip as any for foreign host access. Main VM privilage.
  config.vm.network "forwarded_port", id: 'ssh', auto_correct: true, guest: 22, host: 2222
  config.vm.network "forwarded_port", id: 'docker-registry', auto_correct: true, guest: 5000, host: 5000

  # NOTE map vagrantfiles/public, a share seen by all local vagrant VMs
  config.vm.synced_folder  '../public', "/vagrant/public"
  # NOTE For dotfiles, another privilage for main VM
  WINHOME = ENV['HOMEDRIVE'] + "/" + ENV['HOMEPATH']
  config.vm.synced_folder  WINHOME + "/Dropbox", "/Dropbox"

  config.vm.provider "virtualbox" do |vb|
    # As 20160725, crystal box is using docker for most local development and
    # thus a larger memory is needed.
    vb.memory = "1024"
    # NOTE sync time of guest every 10 secs instead of default 20 mins. Some
    # system programs like `systemd-logind` depends on it.
    vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
  end

  # Provision personal configurations, system-wide changes should be in the base
  # box creation. Do NOT RUN with SUDO
  config.vm.provision "shell", privileged: false, path: 'provision.sh'
end
