# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "crystal-maker"

  config.vm.hostname = "crystal"
  config.vm.box_check_update = false

  # For personal use, do not generate new pair of keys.
  config.ssh.insert_key = false


  # NOTE about hostname resolution.
  #
  # 1. Use static private ip.
  # 2. Map the windows' host file to the vm, s.t. it can serve as a central
  # registry.
  # 3. The registry is managed manually, see 'Vagrantfile-dhcp-with-host' file for
  # auto-managed method
  #
  config.vm.network "private_network", ip: "192.168.56.7"
  config.vm.synced_folder  ENV["WINDIR"] + "/System32/drivers", "/tmp/windrivers"
  # FIX: the following can mount hosts file multiple times for suspend/resume use cases
  config.vm.provision "shell", run: "always", name: "bind-hosts",
                      inline: "mount --bind /tmp/windrivers/etc/hosts /etc/hosts"

  # Other than the default '.' => '/vagrant'
  WINHOME = ENV['HOMEDRIVE'] + "/" + ENV['HOMEPATH']
  config.vm.synced_folder  WINHOME + "/Dropbox", "/Dropbox"

  config.vm.provider "virtualbox" do |vb|
    # As 20160725, crystal box is using docker for most local development and
    # thus a larger memory is needed.
    vb.memory = "1024"
    # NOTE a very IMPORTANT setting! This forces VBoxService to sync time every
    # 10 secs instead of the default 20 mins, which may cause fatal errors from
    # `systemd-logind` that freeze the whole system (this happens after I
    # suspending the post for several times)
    # Ref: http://stackoverflow.com/a/19492466
    # Another ref that offers more explanation and settings, though it's not about Vagrant: http://superuser.com/a/765014
    vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
  end

  # Provision personal configurations, system-wide changes should be in the base
  # box creation. Do NOT RUN with SUDO
  config.vm.provision "shell", privileged: false, path: 'crystal-provision.sh'
end
