# -*- mode: ruby -*-
# vi: set ft=ruby :

# Build machine using docker

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.box_check_update = false
  config.ssh.insert_key = false

  config.vm.network "private_network", type: "dhcp"
  config.vm.hostname = "ceph-builder"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = 16384
     vb.cpus= 4
  end

  # config.vm.provision "shell", inline: <<-SHELL
  # SHELL
end
