# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # For making box purpose, do not insert new key
  config.ssh.insert_key = false

  # From minimalistic to more-up-to-date box
  # see https://github.com/terrywang/vagrantboxes/blob/master/archlinux-x86_64.md
  config.vm.box = "terrywang/archlinux"

  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    # Enough RAM to avoid installation errors
    vb.memory = "1024"
  end

  # NOTE shell script should be in unix line ending style
  config.vm.provision "shell", path: 'provision.sh'
end
