# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All SLE boxes are managed locally.
  config.vm.box = "ses3-builder-20170106"
  config.vm.box_check_update = false

  # If not for other "serious" purpose, keep it simple
  config.ssh.insert_key = false

  # TODO we need better way to keep track of all those VMs.
  config.vm.network "private_network", ip: "192.168.56.60"
  config.vm.hostname = "ses3-builder"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "8192"
  end

  # config.vm.provision "shell", inline: <<-SHELL
  # SHELL
end
